import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'chrome', headless: true });
const c = await b.newContext({ viewport: { width: 1440, height: 1000 } });
await c.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
const p = await c.newPage();
const errs = []; p.on('pageerror', e => errs.push(String(e)));
await p.goto('http://127.0.0.1:5173/console.html', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(900);
await p.getByText('平台登录').click(); await p.waitForTimeout(300);
const ins = p.locator('input'); await ins.nth(0).fill('admin'); await ins.nth(1).fill('admin123');
await p.getByRole('button', { name: /登录/ }).first().click(); await p.waitForTimeout(1800);
await p.getByRole('button', { name: '内容管理' }).first().click(); await p.waitForTimeout(1200);
await p.screenshot({ path: 'e2e/audit/content-01-announce.png', fullPage: true });
await p.getByRole('button', { name: '资讯' }).first().click(); await p.waitForTimeout(1200);
await p.screenshot({ path: 'e2e/audit/content-02-news.png', fullPage: true });
await p.getByRole('button', { name: /新建资讯/ }).first().click(); await p.waitForTimeout(700);
await p.screenshot({ path: 'e2e/audit/content-03-newmodal.png', fullPage: true });
console.log('错误:', errs.length ? errs : '无');
await b.close();
