import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'chrome', headless: true });
const p = await (await b.newContext({ viewport: { width: 1280, height: 900 } })).newPage();
const errs=[]; p.on('pageerror', e=>errs.push(e.message));
await p.goto('http://127.0.0.1:5173/console.html', { waitUntil: 'domcontentloaded' });
await p.getByRole('radio', { name: '平台登录' }).first().click();
await p.locator('form input').nth(0).fill('admin');
await p.locator('form input').nth(1).fill('admin123');
await p.getByRole('button', { name: /^登录$/ }).first().click();
await p.locator('aside nav button', { hasText: '提现审核' }).first().waitFor({ timeout: 12000 });
await p.locator('aside nav button', { hasText: '提现审核' }).first().click();
await p.waitForTimeout(2000);
const root = await p.locator('main').innerText().catch(()=>'');
console.log('=== 提现审核页文本(前600)===\n'+root.slice(0,600));
const approveBtns = await p.getByRole('button', { name: /通过打款|通过/ }).count();
console.log('\n通过打款按钮数:', approveBtns);
console.log('JS错误:', errs.length? errs.join(' | '):'无');
await p.screenshot({path:'e2e/dbg-wd.png'});
await b.close();
