import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await b.newContext({ viewport: { width: 420, height: 880 } });
const page = await ctx.newPage();
ctx.on('page', p => { if (p !== page) p.close().catch(()=>{}); });
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'domcontentloaded' });
await page.getByText('演示商品').first().waitFor({ timeout: 15000 });
await page.screenshot({ path: 'e2e/shot-home.png', fullPage: true });
console.log('home ok');
await page.getByText('演示商品').first().click();
await page.getByRole('button', { name: /购买/ }).first().waitFor({ timeout: 10000 });
await page.screenshot({ path: 'e2e/shot-detail.png', fullPage: true });
console.log('detail ok');
const email = page.locator('input[type="email"], input[placeholder*="邮箱"], input[placeholder*="@"]').first();
if (await email.count()) await email.fill('buyer@demo.com'); else await page.locator('input').first().fill('buyer@demo.com');
await page.getByRole('button', { name: /购买/ }).first().click();
await page.getByRole('button', { name: /确认支付/ }).first().waitFor({ timeout: 15000 });
await page.screenshot({ path: 'e2e/shot-pay.png', fullPage: true });
console.log('pay ok');
await b.close();
